### ISSUE TITLE
Entire Site is not scrollable

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#1217]
![Screenshot 2019-05-01 at 1 27 48 PM](https://user-images.githubusercontent.com/39734400/57009572-f65dd100-6c14-11e9-9eaa-fb19a3ee06d3.png)

**Comment by anban4u** [comment]
I can see this scrolling on my browser. Which browser are you using?

**Comment by anban4u** [comment]
I can see no scroll on brave.

@akanksha-10 lets investigate this on priority. Also, can we mention which browsers are working for now?

I have opera - where it is working and brave where it is not.

**Comment by anban4u** [comment]
I dont see scroll on chrome or edge as well.

**Comment by anban4u** [comment]
The scroll seems to work on these browsers for mobile screen sizes though. So it has to do something with one of the xs changes we probably made. When was the last dashboard build?

**Comment by crayonflakesmanu** [comment]
I have chrome and it is not working on it. Have recorded my screen if it helps. 
Also have noticed there is no error on console.


[StompScreenRecording.mov.zip](https://github.com/StompMarket/helpdesk/files/3136760/StompScreenRecording.mov.zip)

On a side note -- should remove console printing from prod.

**Comment by akanksha-10** [comment]
@crayonflakesmanu  Hope you're not facing problem with scrolling anymore as this issue has been fixed and delivered yesterday.

**Comment by crayonflakesmanu** [comment]
Still an issue on this screen

Batch Packages
Manage Your Batch Packages
HS-SOR
