### ISSUE TITLE
If same item scanned twice in the DO, it should not show as 2 items - misleads the count

### ISSUE THREAD

**Issue by crayonflakesmanu** [StompMarket/helpdesk#324]
![screen shot 2018-08-09 at 5 16 54 pm](https://user-images.githubusercontent.com/39734400/43896966-2e7a4cdc-9bf8-11e8-8561-c3b643bde6e7.png)
![screen shot 2018-08-09 at 5 16 49 pm](https://user-images.githubusercontent.com/39734400/43896967-2eb4630e-9bf8-11e8-8f90-bec0a0a6a64a.png)

**Comment by crayonflakesmanu** [comment]
Count (for remaining & packed) in the shipment screen is also not right because of the same reason.

**Comment by crayonflakesmanu** [comment]
another major blocker in this issue -

DO contains 2 items for G1-Set5/16-4_5

Now it does not allows to scan the 2nd item - giving this

![screen shot 2018-08-25 at 9 59 43 am](https://user-images.githubusercontent.com/39734400/44615041-c1130f00-a84d-11e8-9530-3e8f6ddfc5e3.png)

where as attached item is this (present twice)
![screen shot 2018-08-25 at 9 59 49 am](https://user-images.githubusercontent.com/39734400/44615049-ef90ea00-a84d-11e8-9219-330cf71f2da8.png)

**Comment by mukeem1** [comment]
done

**Comment by crayonflakesmanu** [comment]
This does not seems to be solved yet.

See this example-
In PO - 166223 boys refill below items are present twice.
0094SL
0094RB
0094LS

Pls open this issue.

**Comment by crayonflakesmanu** [comment]
This issue is not yet solved. Pls resolve this asap.

![screen shot 2018-10-12 at 10 54 21 am](https://user-images.githubusercontent.com/39734400/46852090-62165300-ce17-11e8-8fad-2ce3c0086082.png)
